### ISSUE TITLE
Feature Request: Split Testing and Building into two actions

### ISSUE THREAD

**Issue by FirefoxMetzger** [ignition-tooling/ubuntu-bionic-ci-action#31]
I just discovered this action, and I think it's really cool; being able to simply do

```
steps:
      [...]
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@bionic
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
      [...]
```

to get the ignition stack for CI testing seems so right and it would be very helpful if downstream packages (like [ropy](https://github.com/FirefoxMetzger/ropy)) can build on this functionality, too. That said, not every downstream package wants to run the whole test suite or upload ignition coverage, and merely building/adding ignition is all that is needed.

Would it be possible to split this action into two actions doing `ignition-tooling/action-ignition-build` and `ignition-tooling/action-ignition-test`?
